spring.application.name=FluxisStore

spring.datasource.url=jdbc:mysql://localhost:3306/crediya
spring.datasource.username=root
spring.datasource.password=root12345
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


//spring.datasource.url=jdbc:mysql://62.72.5.40:3306/fluxis_store
//spring.datasource.username=fluxis
//spring.datasource.password=TuPasswordSeguro123
//spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver